CREATE TABLE dataset (
    datasetID       TEXT PRIMARY KEY ,       -- unique identifier for each ZIP/archive
    format          TEXT,                   -- e.g., "DwC-A","PNG"
    name            TEXT,                   -- optional: dataset title
    information     TEXT,                   
    ingestionDate   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE taxon (
    TaxonID TEXT PRIMARY KEY,                   
    acceptedNameUsage TEXT,
    acceptedNameUsageID TEXT,
    acceptedScientificName TEXT,
    acceptedScientificNameID TEXT,
    acceptedTaxon TEXT,
    AcceptedTaxonID TEXT,
    acceptedTaxonID TEXT,
    acceptedTaxonName TEXT,
    acceptedTaxonNameID TEXT,
    basionym TEXT,
    basionymID TEXT,
    binomial TEXT,
    class TEXT,
    cultivarEpithet TEXT,
    family TEXT,
    genericName TEXT,
    genus TEXT,
    higherClassification TEXT,
    HigherTaxon TEXT,
    higherTaxonconceptID TEXT,
    HigherTaxonID TEXT,
    higherTaxonName TEXT,
    higherTaxonNameID TEXT,
    infragenericEpithet TEXT,
    infraspecificEpithet TEXT,
    kingdom TEXT,
    nameAccordingTo TEXT,
    nameAccordingToID TEXT,
    namePublicationID TEXT,
    namePublishedIn TEXT,
    namePublishedInID TEXT,
    namePublishedInYear TEXT,
    nomenclaturalCode TEXT,
    nomenclaturalStatus TEXT,
    order_name TEXT,
    originalNameUsage TEXT,
    originalNameUsageID TEXT,
    parentNameUsage TEXT,
    parentNameUsageID TEXT,
    phylum TEXT,
    scientificName TEXT,
    scientificNameAuthorship TEXT,
    scientificNameID TEXT,
    scientificNameRank TEXT,
    specificEpithet TEXT,
    subfamily TEXT,
    subgenus TEXT,
    subtribe TEXT,
    superfamily TEXT,
    taxonAccordingTo TEXT,
    taxonAttributes TEXT,
    taxonConceptID TEXT,
    taxonNameID TEXT,
    taxonomicStatus TEXT,
    taxonRank TEXT,
    taxonRemarks TEXT,
    tribe TEXT,
    verbatimScientificNameRank TEXT,
    verbatimTaxonRank TEXT,
    vernacularName TEXT
);
