CREATE TABLE project (
    project INTEGER,
    name TEXT,
    project_id TEXT PRIMARY KEY,
    description TEXT
);

CREATE TABLE dataset (
    dataset_id       TEXT PRIMARY KEY,      
    project_id       TEXT,
    format          TEXT,                   
    name            TEXT,
    author_id       TEXT,                  
    description     TEXT,                   
    keywords        TEXT,
    date_published   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataset_link TEXT,
    FOREIGN KEY (project_id) REFERENCES project(project_id)
);

CREATE TABLE taxon (
    taxon_id TEXT PRIMARY KEY,                   
    acceptedNameUsage TEXT,
    acceptedNameUsageID TEXT,
    acceptedScientificName TEXT,
    acceptedScientificNameID TEXT,
    acceptedTaxon TEXT,
    acceptedTaxonID TEXT,
    acceptedTaxonName TEXT,
    acceptedTaxonNameID TEXT,
    basionym TEXT,
    basionymID TEXT,
    binomial TEXT,
    class TEXT,
    cultivarEpithet TEXT,
    family TEXT,
    genericName TEXT,
    genus TEXT,
    higherClassification TEXT,
    HigherTaxon TEXT,
    higherTaxonconceptID TEXT,
    HigherTaxonID TEXT,
    higherTaxonName TEXT,
    higherTaxonNameID TEXT,
    infragenericEpithet TEXT,
    infraspecificEpithet TEXT,
    kingdom TEXT,
    nameAccordingTo TEXT,
    nameAccordingToID TEXT,
    namePublicationID TEXT,
    namePublishedIn TEXT,
    namePublishedInID TEXT,
    namePublishedInYear TEXT,
    nomenclaturalCode TEXT,
    nomenclaturalStatus TEXT,
    order_name TEXT,
    originalNameUsage TEXT,
    originalNameUsageID TEXT,
    parentNameUsage TEXT,
    parentNameUsageID TEXT,
    phylum TEXT,
    scientificName TEXT,
    scientificNameAuthorship TEXT,
    scientificNameID TEXT,
    scientificNameRank TEXT,
    specificEpithet TEXT,
    subfamily TEXT,
    subgenus TEXT,
    subtribe TEXT,
    superfamily TEXT,
    taxonAccordingTo TEXT,
    taxonAttributes TEXT,
    taxonConceptID TEXT,
    taxonNameID TEXT,
    taxonomicStatus TEXT,
    taxonRank TEXT,
    taxonRemarks TEXT,
    tribe TEXT,
    verbatimScientificNameRank TEXT,
    verbatimTaxonRank TEXT,
    vernacularName TEXT
);

CREATE TABLE occurrence (
    occurrence_id TEXT PRIMARY KEY,
    sex TEXT,
    behavior TEXT,
    preparations TEXT,
    disposition TEXT,
    year INTEGER,
    month INTEGER,
    day INTEGER,
    habitat TEXT,
    locality TEXT,
    country TEXT,
    county TEXT,
    municipality TEXT,
    continent TEXT,
    catalog_number TEXT,
    occurrence_status TEXT,
    basis_of_record TEXT,
    recorded_by TEXT,
    individual_count INTEGER,
    life_stage TEXT,
    establishment_means TEXT,
    event_date DATE,
    start_day_of_year INTEGER,
    end_day_of_year INTEGER,
    sampling_protocol TEXT,
    field_notes TEXT,
    decimal_latitude DECIMAL,
    decimal_longitude DECIMAL,
    coordinate_uncertainty_in_meters DECIMAL,
    geodetic_datum TEXT,
    coordinate_precision DECIMAL,
    verbatim_locality TEXT,
    state_province TEXT,
    water_body TEXT,
    minimum_depth_in_meters DECIMAL,
    maximum_depth_in_meters DECIMAL,
    minimum_elevation_in_meters DECIMAL,
    maximum_elevation_in_meters DECIMAL,
    verbatim_coordinates TEXT,
    verbatim_coordinate_system TEXT,
    verbatim_srs TEXT,
    dataset_id TEXT,
    taxon_id TEXT,
    institution_code TEXT,
    collection_code TEXT,
    recorded_by_id TEXT,
    identified_by TEXT,
    date_identified DATE,
    occurrence_remarks TEXT,
    project_id TEXT,
    FOREIGN KEY (dataset_id) REFERENCES dataset(dataset_id),
    FOREIGN KEY (taxon_id) REFERENCES taxon(taxon_id),
    FOREIGN KEY (project_id) REFERENCES project(project_id)
);

CREATE TABLE multimedia (
    multimedia_id TEXT PRIMARY KEY,
    project_id TEXT,
    dataset_id TEXT,
    occurrence_id TEXT,
    taxon_id TEXT,
    title TEXT,
    description TEXT,
    format TEXT,
    license TEXT,
    rights_holder TEXT,
    creator TEXT,
    contributor TEXT,
    publisher TEXT,
    date_created DATE,
    date_uploaded DATE,
    source TEXT,
    reference TEXT,
    type TEXT,
    audience TEXT,
    audience_remarks TEXT,
    location TEXT,
    latitude DECIMAL,
    longitude DECIMAL,
    altitude DECIMAL,
    specimen_voucher TEXT,
    other_catalog_numbers TEXT,
    multimedia_link TEXT,
    FOREIGN KEY (project_id) REFERENCES project(project_id),
    FOREIGN KEY (dataset_id) REFERENCES dataset(dataset_id),
    FOREIGN KEY (occurrence_id) REFERENCES occurrence(occurrence_id),
    FOREIGN KEY (taxon_id) REFERENCES taxon(taxon_id)
);

CREATE TABLE sequences (
    sequence_id TEXT PRIMARY KEY,
    dataset_id TEXT,
    project_id TEXT,
    occurrence_id TEXT,
    taxon_id TEXT,
    sequence_type TEXT,
    sequence TEXT,
    sequence_length INTEGER,
    sequence_link TEXT,
    gene_region TEXT,
    locus TEXT,
    accession_number TEXT,
    database_name TEXT,
    specimen_voucher TEXT,
    sampling_protocol TEXT,
    collection_date DATE,
    collector TEXT,
    reference TEXT,
    FOREIGN KEY (dataset_id) REFERENCES dataset(dataset_id),
    FOREIGN KEY (project_id) REFERENCES project(project_id),
    FOREIGN KEY (occurrence_id) REFERENCES occurrence(occurrence_id),
    FOREIGN KEY (taxon_id) REFERENCES taxon(taxon_id)
);

CREATE TABLE measurementorfact (
    measurement_id TEXT PRIMARY KEY,
    measurement_accuracy DECIMAL,
    measurement_determined_by TEXT,
    measurement_determined_date DATE,
    measurement_method TEXT,
    measurement_remarks TEXT,
    measurement_type TEXT,
    measurement_unit TEXT,
    measurement_value DECIMAL,
    parent_measurement_id TEXT,
    verbatim_measurement_type TEXT,
    dataset_id TEXT,
    occurrence_id TEXT,
    taxon_id TEXT,
    project_id TEXT,
    locality TEXT,
    verbatim_locality TEXT,
    country TEXT,
    state_province TEXT,
    county TEXT,
    municipality TEXT,
    continent TEXT,
    water_body TEXT,
    decimal_latitude DECIMAL,
    decimal_longitude DECIMAL,
    coordinate_uncertainty_in_meters DECIMAL,
    geodetic_datum TEXT,
    coordinate_precision DECIMAL,
    minimum_elevation_in_meters DECIMAL,
    maximum_elevation_in_meters DECIMAL,
    minimum_depth_in_meters DECIMAL,
    maximum_depth_in_meters DECIMAL,
    FOREIGN KEY (dataset_id) REFERENCES dataset(dataset_id),
    FOREIGN KEY (project_id) REFERENCES project(project_id)
);
